### PR TITLE
DM-9606: Fix Python package structure

### PR DESCRIPTION
**Pull request by jonathansick**
The `lsst/` base directory was missing.

### CODE REVIEW

**Comment by parejkoj** [comment]
Do we really want any python files in here at all? This isn't a package that will be "python imported" ever.

**Comment by jonathansick** [comment]
Idea is that `lsst.validate.metrics.__version__` might be important as its the native way of establishing package versions in the Stack. Otherwise, there's no Python.

**Comment by parejkoj** [comment]
Hmm... We don't have another way to track versions? It'd be a bit confusing to have a totally empty python module structure, and might tempt people to add python code to it.

**Comment by jonathansick** [comment]
Other than interacting with git repositories on the file system or EUPS, we don't afaik.

**Comment by jonathansick** [comment]
I could add a README in the Python path reminding contributors not to add code to `validate_metrics`, and look at `validate_base` instead.

**Comment by parejkoj** [comment]
Yes, I think a readme would be appropriate, or a note in the base-level readme.

**Comment by jonathansick** [comment]
Does the README addition work for your @parejkoj ?

**Pull request merged**
